"""empty message

Revision ID: 293c980d0c20
Revises: 
Create Date: 2024-09-19 19:59:52.372617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293c980d0c20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('award_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boost_reputation_vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('boost_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_name_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=17), nullable=False),
    sa.Column('game_balance', sa.Integer(), nullable=False),
    sa.Column('site_balance', sa.Integer(), nullable=False),
    sa.Column('vip', sa.Boolean(), nullable=False),
    sa.Column('vip_lvl', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.JSON(), nullable=False),
    sa.Column('created_at_player', sa.DateTime(), nullable=False),
    sa.Column('created_at_vip', sa.DateTime(), nullable=True),
    sa.Column('date_end_vip', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id')
    )
    op.create_table('reputation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('static', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stash_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('awards_list', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('reputation_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('orientation', sa.String(length=100), nullable=False),
    sa.Column('clothes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['reputation_type_id'], ['reputation_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('orientation', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_opened', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stash_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('daily', 'weekly', 'monthly', 'lore', name='questtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('awards_api', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('required_items', sa.JSON(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('reputation_need', sa.Integer(), nullable=False),
    sa.Column('reputation_add', sa.Integer(), nullable=False),
    sa.Column('reputation_minus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['awards_api'], ['award_api.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('award_take', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('quest')
    op.drop_table('stash')
    op.drop_table('operator')
    op.drop_table('stash_category')
    op.drop_table('reputation_type')
    op.drop_table('player')
    op.drop_table('game_name_animal')
    op.drop_table('boost_reputation_vip')
    op.drop_table('award_api')
    op.drop_table('action')
    # ### end Alembic commands ###
